AWSTemplateFormatVersion: '2010-09-09'
Description: Formation para WebServer 35CLD Infra com ECS e ECR

Parameters:
  VpcCidr:
    Type: String
    Default: 10.0.0.0/16
  Subnet1Cidr:
    Type: String
    Default: 10.0.1.0/24
  Subnet2Cidr:
    Type: String
    Default: 10.0.2.0/24
  Subnet3Cidr:
    Type: String
    Default: 10.0.3.0/24
  ECSOptimizedAMI:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id"
    Description: "Latest Amazon ECS-Optimized AMI."

Resources:

# ==========================
# 3. ECS Cluster e EC2 Instance
# ==========================

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: "MyECSCluster"

  ECSInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "ECSInstanceRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: 
                - "ec2.amazonaws.com"
                - "ecs-tasks.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "ECSInstancePassRolePolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "iam:PassRole"
                Resource: !Sub "arn:aws:iam::${AWS::AccountId}:role/ECSInstanceRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role"
        - "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"

  ECSInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: "ECSInstanceProfile"
      Roles:
        - !Ref ECSInstanceRole

  ECSInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: "t2.micro"
      ImageId: !Ref ECSOptimizedAMI
      IamInstanceProfile: !Ref ECSInstanceProfile
      SecurityGroupIds:
        - !Ref SGWEBServer
      SubnetId: !Ref WebServerPublicSubnet1
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          echo ECS_CLUSTER=${ECSCluster} >> /etc/ecs/ecs.config
      Tags:
        - Key: Name
          Value: ECSInstance

# ==========================
# 6. ECS Service 
# ==========================

  ECSService:
    Type: AWS::ECS::Service
    DependsOn: ECSTaskDefinition
    Properties:
      Cluster: !Ref ECSCluster
      ServiceName: "WebserverService"
      TaskDefinition: !Ref ECSTaskDefinition
      DesiredCount: 1
      LaunchType: EC2
      DeploymentConfiguration:
        MinimumHealthyPercent: 100
        MaximumPercent: 200
      SchedulingStrategy: REPLICA
