AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation para criar um Security Group referenciando a VPC de outro stack"

Resources:
  SGWEBServer:
    Type: AWS::EC2::SecurityGroup
    Properties:
      # Nome do Security Group
      GroupName: "SGWEBServer"
      GroupDescription: "Security Group para Web Server"
      
      # Importa o VPC ID exportado pelo outro stack
      VpcId: !ImportValue WebServerVPCId

      # Regras de entrada
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 177.160.133.69/32

      # Regras de saída 
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: 0.0.0.0/0
